services:
  web:
    image: nginx
    #из локального копирует в гостевую
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "82:80"
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build: ./docker/Php
    restart: always
    volumes:
#      - ./docker/Php:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
      - ./docker/Php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    env_file:
      - .env
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "54324:5432"
    volumes:
      - ./sourcefiles/postgres:/var/lib/postgresql/data
